### ISSUE TITLE
A couple random things

### ISSUE THREAD

**Issue by dmrickey** [kristkos/KCTG-1e#1]
The link in the readme isn't publicly visible - is that intentional even though the mod is publicly available?

The image on the foundry page doesn't seem to be linked to a real image
![image](https://github.com/user-attachments/assets/be8cc6ad-edaa-45ea-a26c-94fd358b35cc)

**Comment by kristkos** [comment]
For the read-me, it's set to "Free Tier". For the when it was fully public, I had some complaints that it was really hard to find, even when it was pinned, it wasn't at the top for whatever reason. The "Free tier" fixed that issue. 

About the image I will change shortly. As the description of the module is not something I edit constantly, I had overlooked it.

**Comment by kristkos** [comment]
The banner should be sorted now. Let me know if you see any other discrepancies.

Edit: If you happen to know how to fix that on Patreon, would love to know.

**Comment by dmrickey** [comment]
For patreon, the readme here links directly to a post which doesn't appear to be public. If you've got a public post that has the information, you can change the link to that instead. 

It looks like the post is not publicly available because it's tied to a specific patreon tier. Even if the tier is free, I'm not going to sign up just to know what's in a mod ¯\\\_(ツ)_/¯.

**Comment by kristkos** [comment]
It is currently public.
